# Numpy Tutorial

In [15]:
import numpy as np
a = np.array([1,2,3], np.int8)
print(a)
print(a[1])   # select element from array
print(a.ndim) # array daimansion
print(type(a)) # Type of variable
print(a.dtype) # Data Type
print(a.shape) # shape(column,element)
print(a.size)

[1 2 3]
2
1
<class 'numpy.ndarray'>
int8
(3,)
3


In [13]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)
print("==================")
print(a.shape)
print("==================")
print(a.reshape(3,2))

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [14]:
import numpy as np

a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


**Array creation: Conversion from other Python structures**

In [22]:
list_array = np.array([[1,2,3],[5,8,5],[0,3,1]])

print(list_array)
print(list_array.dtype)
print(list_array.shape)
list_array.size

[[1 2 3]
 [5 8 5]
 [0 3 1]]
int64
(3, 3)


9

In [23]:
np.array({34,35,20})

array({34, 35, 20}, dtype=object)

In [26]:
zeros = np.zeros((2,5))
zeros
zeros.dtype
zeros.shape

(2, 5)

In [27]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [36]:
emp = np.empty((4,6))
emp

array([[3.05368300e-316, 7.01573217e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 3.16251369e+180],
       [1.05776693e-153, 6.03461190e+151, 8.95412132e-096,
        1.67772392e+243, 1.16466606e-028, 4.90900643e+252],
       [1.94918511e-153, 3.00833776e+151, 9.03292974e+271,
        6.96411098e+252, 5.49740424e-095, 3.16251369e+180],
       [3.65588338e+233, 8.61882260e+183, 2.59050147e-144,
        1.16442250e-028, 6.79769037e-310, 0.00000000e+000]])

In [38]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [39]:
ide.shape

(45, 45)

In [42]:
arr = np.arange(99)
arr # --> [0,1,2,.....,98] get this array
arr.reshape(3,33)
arr.ravel() # --> convert in old array.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

**Numpy Slicing**

In [55]:
arr = [1,2,3,4,5]
"""
||=================||
||  0  1  2  3  4  ||
||  |  |  |  |  |  ||
|| [1, 2, 3, 4, 5] ||
||  |  |  |  |  |  ||
|| -5 -4 -3 -2 -1  ||
||=================||
"""
# arr[start,stop,step]
print(arr)
print(arr[0:4])
print(arr[2:-1])
print(arr[0:4:2])
print(arr[::2])
print(arr[2::])
print(arr[:2:])
print(arr[])

[1, 2, 3, 4, 5]
[1, 2, 3, 4]
[3, 4]
[1, 3]
[1, 3, 5]
[3, 4, 5]
[1, 2]


**NumPy Axis**