In [ ]:
import numpy as np
a = np.arange(0,10,1)
print(a)
print("=======================")
b = np.linspace(0,1,11)
print(b)
print("=======================")
re1 = np.random.randint(1,100,10)
re2 = re1.reshape(5,2)
print(re1)
print("=======================")
print(re2)
print("=======================")
c = [[1, 2], [4, 1]]  
d = [[4, 11], [2, 3]]  
e =np.dot(c, d) 
print(e)

[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[98  6 65 38 11 97 34  6 30 18]
[[98  6]
 [65 38]
 [11 97]
 [34  6]
 [30 18]]
[[ 8 17]
 [18 47]]


In [ ]:
import numpy as np
a1 = np.any([[True, False], [False, False]],axis=0)
a2 = np.any([[True, False], [False, False]])
print(a1)
print(a2)
a3 = np.any([-1, 0, 5])
print(a3)
print("=======================")
a4 = np.any([[True, False], [False, False]], where=[[False], [True]],axis=0)
print(a4)
print("=======================")
o=np.array(False)
z=np.any([-1, 4, 5], out=o)
print(z,o)
# Check now that z is a reference to o
print(z is o)
print(id(z),id(o))

[ True False]
True
True
[False False]
True True
True
139691673050256 139691673050256


In [ ]:
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j], dtype=complex)
np.isreal(a)

array([False,  True,  True,  True,  True, False])

In [ ]:
import numpy as np
np.all([[True,False],[True,True]])
np.all([[True,False],[True,True]],axis=0)

array([ True, False])

In [ ]:
import numpy as np
np.iscomplex([1+1j, 1+0j, 4.5, 3, 2, 2j])

In [ ]:
import numpy as np
np.isnan(np.nan)
np.isnan(np.inf)
np.isnan([np.log(-1.),1.,np.log(0)])

In [ ]:
import numpy as np
np.isscalar(3.1)
np.isscalar(np.array(3.1))
np.isscalar([3.1])
np.isscalar(False)
np.isscalar('numpy')

In [ ]:
import numpy as np
np.isinf(np.inf)
np.isinf(np.nan)
np.isinf(np.NINF)
np.isinf([np.inf, -np.inf, 1.0, np.nan])

x = np.array([-np.inf, 0., np.inf])
y = np.array([2, 2, 2])
np.isinf(x,y)


array([1, 0, 1])

In [ ]:
import numpy as np
a = np.array([1, 2])
b = np.array([2, 2])
np.less(a,b)

# OR >>> np.less([1,2],[2,2])
#    array([ True, False])

a = np.array([4, 2])
b = np.array([2, 2])
np.greater(a,b)

np.less_equal([4, 2, 1], [2, 2, 2])
np.greater_equal([4, 2, 1], [2, 2, 2])

array([ True,  True, False])

In [ ]:
import numpy as np
np.isfinite(1)
np.isfinite(0)
np.isfinite(np.nan)
np.isfinite(np.inf)
np.isfinite(np.NINF)

x = np.array([-np.inf, 0., np.inf])
y = np.array([2, 2, 2])
np.isfinite(x, y)
np.isfinite(y)

array([ True,  True,  True])

In [ ]:
import numpy as np
c = np.zeros(3)
print(c)
c1 = np.zeros((2,3))
print(c1)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
a1 = np.any([[True, False], [False, False]],axis=0)
a2 = np.any([[True, False], [False, False]])
print(a1)
print(a2)
print("=======================")
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j], dtype=complex)
print(np.isreal(a))
print("=======================")
b1 = np.all([[True,False],[True,True]])
b2 = np.all([[True,False],[True,True]],axis=0)
print(b1)
print(b2)
print("=======================")
print(np.iscomplex([1+1j, 1+0j, 4.5, 3, 2, 2j]))
print("=======================")
print(np.isnan(np.nan))
print(np.isnan(np.inf))
print(np.isnan([np.log(-1.),1.,np.log(0)]))
print("=======================")
print(np.isscalar(3.1))
print(np.isscalar(np.array(3.1)))
print(np.isscalar([3.1]))
print(np.isscalar(False))
print(np.isscalar('numpy'))
print("=======================")
x = np.array([-np.inf, 0., np.inf])
y = np.array([2, 2, 2])
print(np.isinf(x,y))
print("=======================")
a = np.array([1, 2])
b = np.array([2, 2])
print(np.less(a,b))
print("=======================")
a = np.array([4, 2])
b = np.array([2, 2])
print(np.greater(a,b))
print("=======================")
print(np.less_equal([4, 2, 1], [2, 2, 2]))
print("=======================")
print(np.greater_equal([4, 2, 1], [2, 2, 2]))
print("=======================")
x = np.array([-np.inf, 0., np.inf])
y = np.array([2, 2, 2])
print(np.isfinite(x, y))
print(np.isfinite(y))
print("=======================")
c = np.zeros(3)
print(c)
c1 = np.zeros((2,3))
print(c1)

[ True False]
True
[False  True  True  True  True False]
False
[ True False]
[ True False False False False  True]
True
False
[ True False False]
True
False
False
True
True
[1 0 1]
[ True False]
[ True False]
[False  True  True]
[ True  True False]
[0 1 0]
[ True  True  True]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in log
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in log
